{% set name = "pyfiglet" %}
{% set version = "1.0.1" %}
{% set compress_type = "tar.gz" %}
{% set hash = "c7d9088a6f821bdf69c58d9757378085a76881626b2308e6bbda707121607f18" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash }}

build:
  noarch: python
  entry_points:
    - pyfiglet = pyfiglet:main
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - pyfiglet
    - pyfiglet.fonts

  commands:
    - pyfiglet --help

about:
  home: https://github.com/pwaller/pyfiglet
  summary: 'Pure-python FIGlet implementation'
  # license_file not in MANIFEST, so including local copy - see https://github.com/pwaller/pyfiglet/pull/52
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: GPL2
  license_family: GPL2
  dev_url: https://github.com/pwaller/pyfiglet

extra:
  recipe-maintainers:
    - pmlandwehr
