{% set name = "pyfiglet" %}
{% set version = "0.7.6" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "97d59651b40da6ddf7e961157c480a7a04b48214d8c7231adc8c15e43aa5d722" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  entry_points:
    - pyfiglet = pyfiglet:main
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - pyfiglet
    - pyfiglet.fonts

  commands:
    - pyfiglet --help

about:
  home: https://github.com/pwaller/pyfiglet
  summary: 'Pure-python FIGlet implementation'
  # license_file not in MANIFEST, so including local copy - see https://github.com/pwaller/pyfiglet/pull/52
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: GPL2
  license_family: GPL2
  dev_url: https://github.com/pwaller/pyfiglet

extra:
  recipe-maintainers:
    - pmlandwehr
